// <auto-generated />
using System;
using API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Model.Book", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(8)")
                        .HasColumnName("Id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Author");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("BookTitle");

                    b.Property<string>("PublicationYear")
                        .IsRequired()
                        .HasColumnType("varchar(4)")
                        .HasColumnName("PublicationYear");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Publisher");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("API.Model.Borrow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("B_BookId")
                        .HasColumnType("char(8)")
                        .HasColumnName("BookId");

                    b.Property<string>("B_MemberId")
                        .HasColumnType("char(8)")
                        .HasColumnName("MemberId");

                    b.Property<DateTime?>("BorrowDate")
                        .HasColumnType("datetime")
                        .HasColumnName("BorrowDate");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Returndate");

                    b.HasKey("Id");

                    b.HasIndex("B_BookId");

                    b.HasIndex("B_MemberId");

                    b.ToTable("Borrow");
                });

            modelBuilder.Entity("API.Models.AccountRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("char(8)")
                        .HasColumnName("AccountId");

                    b.Property<int>("Roleid")
                        .HasColumnType("int")
                        .HasColumnName("Roleid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Roleid");

                    b.ToTable("AccountRoles");
                });

            modelBuilder.Entity("API.Models.Accounts", b =>
                {
                    b.Property<string>("memberId")
                        .HasColumnType("char(8)")
                        .HasColumnName("memberId");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.HasKey("memberId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("API.Models.Member", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(8)")
                        .HasColumnName("Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LastName");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("API.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("API.Model.Borrow", b =>
                {
                    b.HasOne("API.Model.Book", "Book")
                        .WithMany("Borrow")
                        .HasForeignKey("B_BookId");

                    b.HasOne("API.Models.Member", "Member")
                        .WithMany("Borrow")
                        .HasForeignKey("B_MemberId");

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("API.Models.AccountRoles", b =>
                {
                    b.HasOne("API.Models.Accounts", "Accounts")
                        .WithMany("AccountRoles")
                        .HasForeignKey("AccountId");

                    b.HasOne("API.Models.Roles", "Roles")
                        .WithMany("AccountRoles")
                        .HasForeignKey("Roleid");

                    b.Navigation("Accounts");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("API.Models.Accounts", b =>
                {
                    b.HasOne("API.Models.Member", "Member")
                        .WithOne("Accounts")
                        .HasForeignKey("API.Models.Accounts", "memberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("API.Model.Book", b =>
                {
                    b.Navigation("Borrow");
                });

            modelBuilder.Entity("API.Models.Accounts", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("API.Models.Member", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Borrow");
                });

            modelBuilder.Entity("API.Models.Roles", b =>
                {
                    b.Navigation("AccountRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
